In [1]:
import numpy as np

In [2]:
S = np.array([[1, 0.4508],[0.4508,1]])
print(S)
H_core = np.array([[-2.6527, -1.3472],[-1.3472, -1.7318]])
print(H_core)

[[1.     0.4508]
 [0.4508 1.    ]]
[[-2.6527 -1.3472]
 [-1.3472 -1.7318]]


In [3]:
print(1/np.sqrt(2))

0.7071067811865475


In [4]:
U = np.array([[0.707, 0.707],[0.707, -0.707]])

In [5]:
print(np.linalg.eig(S))

EigResult(eigenvalues=array([1.4508, 0.5492]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


In [6]:
print(S@(np.linalg.eig(S)[1]))

[[ 1.02587052 -0.38834304]
 [ 1.02587052  0.38834304]]


In [7]:
U = np.linalg.eig(S)[1]
print(U)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [8]:
s = np.round(U.T@S@U,4)
print(np.diagonal(s))
s_diagonal = 1/np.sqrt(np.diagonal(s))
print(s_diagonal)
s_half = np.diag(s_diagonal)
print(s_half)

[1.4508 0.5492]
[0.8302258  1.34938145]
[[0.8302258  0.        ]
 [0.         1.34938145]]


In [9]:
X_can = U@s_half

In [10]:
X_can
print(X_can)

[[ 0.58705829 -0.95415677]
 [ 0.58705829  0.95415677]]


In [21]:
X_can = np.array([[0.5871,0.9541], [0.5871, -0.9541]])
print(X_can)

[[ 0.5871  0.9541]
 [ 0.5871 -0.9541]]


## storing two-electron integrals forms a necessary part of the calculations. In case of real orbitals, inherent symmetry of the two electron integrals leads to a reduction in the number of in-equivalent integrals (see szabo ostlund example 3.14). Also, look at Yoshimine sorting on wikipedia to store the two electron integrals.

In [22]:
## lets create an order 4 tensor to save the two electron integrals. NOTE: this might not be a memory efficient way to do it
two_electron_integrals = np.zeros((2,2,2,2))
print(two_electron_integrals.shape)

(2, 2, 2, 2)


In [23]:
two_electron_integrals[0,0,0,0] = 1.3072
two_electron_integrals[1,1,1,1] = 0.7746
two_electron_integrals[0,0,1,1] = 0.6057
two_electron_integrals[1,1,0,0] = 0.6057
two_electron_integrals[0,0,0,1] = 0.4373
two_electron_integrals[0,0,1,0] = 0.4373
two_electron_integrals[1,0,0,0] = 0.4373
two_electron_integrals[0,1,0,0] = 0.4373

two_electron_integrals[1,1,1,0] = 0.3118
two_electron_integrals[1,1,0,1] = 0.3118
two_electron_integrals[1,0,1,1] = 0.3118
two_electron_integrals[0,1,1,1] = 0.3118
two_electron_integrals[1,0,1,0] = 0.1773
two_electron_integrals[1,0,0,1] = 0.1773
two_electron_integrals[0,1,1,0] = 0.1773
two_electron_integrals[0,1,0,1] = 0.1773

In [24]:
print(two_electron_integrals)

[[[[1.3072 0.4373]
   [0.4373 0.6057]]

  [[0.4373 0.1773]
   [0.1773 0.3118]]]


 [[[0.4373 0.1773]
   [0.1773 0.3118]]

  [[0.6057 0.3118]
   [0.3118 0.7746]]]]


In [25]:
##starting iterations

In [27]:
# i = 1
for i in range(1,7):
    if i==1:
        F = H_core
        F_dash = X_can.T@F@X_can
#         print(F_dash)
        epsilon, C_dash = np.linalg.eig(F_dash)
        epsilon = np.diag(epsilon)
#         print(C_dash)
#         print(epsilon)
        C = X_can@C_dash
        number_of_occupied_orbitals = int((C.shape[0])/2)
        P = 2*C[:, :number_of_occupied_orbitals].reshape((-1,1))@C[:, :number_of_occupied_orbitals].reshape((1,-1))
#         print(P)
    else:
        G = np.zeros(F.shape)
        for u in range(F.shape[0]):
            for v in range(F.shape[1]):
                temp_term = 0
                for w in range(two_electron_integrals.shape[2]):
                    for x in range(two_electron_integrals.shape[3]):
                        temp_term += P[w,x]*(two_electron_integrals[u,v,w,x]+(0.5*two_electron_integrals[u,x,w,v]))
                G[u,v] = temp_term
        F = H_core + G
        print('G = ',G)
        F_dash = X_can.T@F@X_can
#         print(F_dash)
        epsilon, C_dash = np.linalg.eig(F_dash)
        epsilon = np.diag(epsilon)
#         print(C_dash)
#         print(epsilon)
        C = X_can@C_dash
        number_of_occupied_orbitals = int((C.shape[0])/2)
        P = 2*C[:, :number_of_occupied_orbitals].reshape((-1,1))@C[:, :number_of_occupied_orbitals].reshape((1,-1))
#         print(P)
        

G =  [[3.75371284 1.34489295]
 [1.34489295 1.48765055]]
G =  [[1.28575598 0.88070652]
 [0.88070652 2.33695477]]
G =  [[3.98143817 1.28367347]
 [1.28367347 1.34320049]]
G =  [[1.30380434 0.89138757]
 [0.89138757 2.33537131]]
G =  [[3.98273322 1.28276093]
 [1.28276093 1.34202057]]
